<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.suite._ErrorHolder-20200124144329" tests="1" file="unittest/suite.py" time="0.000" timestamp="0001-01-01T00:00:00" failures="0" errors="1" skipped="0">
	<testcase classname="tearDownClass (__main__" name="Test)" time="0.000" timestamp="0001-01-01T00:00:00" file="unittests\vaeative_unit.py" line="17">
		<error type="WebDriverException" message="Message: chrome not reachable
  (Session info: chrome=79.0.3945.130)
"><![CDATA[Traceback (most recent call last):
  File "c:/Users/srdesai/VeativeWebVR/unittests/vaeative_unit.py", line 493, in tearDownClass
    cls.driver.close()
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=79.0.3945.130)

]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
