<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test-20200124104638" tests="2" file=".py" time="21.259" timestamp="2020-01-24T10:47:02" failures="0" errors="1" skipped="0">
	<testcase classname="Test" name="test_login_form_validations" time="5.734" timestamp="2020-01-24T10:46:47" file="unittests\vaeative_unit.py" line="156">
		<system-out><![CDATA[logged in successfully
]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
	<testcase classname="Test" name="test_signup_form_validations" time="15.524" timestamp="2020-01-24T10:47:02" file="unittests\vaeative_unit.py" line="174">
		<error type="ElementNotInteractableException" message="Message: element not interactable
  (Session info: chrome=79.0.3945.130)
"><![CDATA[Traceback (most recent call last):
  File "c:/Users/srdesai/VeativeWebVR/unittests/vaeative_unit.py", line 182, in test_signup_form_validations
    btn_element.click()
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=79.0.3945.130)

]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
