<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test-20200124134952" tests="1" file=".py" time="17.109" timestamp="2020-01-24T13:50:13" failures="0" errors="1" skipped="0">
	<testcase classname="Test" name="test_login_form_validations" time="17.109" timestamp="2020-01-24T13:50:13" file="unittests\unity.py" line="17">
		<error type="TimeoutException" message="Message: 
"><![CDATA[Traceback (most recent call last):
  File "c:/Users/srdesai/VeativeWebVR/unittests/unity.py", line 34, in test_login_form_validations
    btn_element3 = WebDriverWait(self.driver,10).until(lambda driver:self.driver.find_element_by_xpath(clicable))
  File "C:\Users\srdesai\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

]]></error>
		<system-out><![CDATA[]]></system-out>
		<system-err><![CDATA[]]></system-err>
	</testcase>
</testsuite>
